### ISSUE TITLE
Any interest in merging efforts?

### ISSUE THREAD

**Issue by ProLoser** [octref/goto-github-repo#1]
I've been working on https://github.com/ProLoser/github-omnibox for a while now and have toyed with the features you provide on this extension. Would you be at all interested in merging extensions?

I've over the years added other features in addition to simple hot-jumping to repos, such as status badges, clean expand/collapse on file diffs, and other shortcuts.

**Comment by octref** [comment]
@ProLoser 
I'm a bit busy now so I don't have time to contribute. My extension works well enough for me, but if you like this feature you can add it to yours. Thanks for the invitation though :beers:
